repo:
  url: 'https://github.com/vanna-ai/vanna.git'
  branch: 'master'
files:
  extensions:
    - '.py'
    - '.ipynb'
    - '.md'
    - '.txt'
    - '.rst'
    - '.json'
    - '.yaml'
    - '.yml'
    - '.toml'
  ignore:
    - '.git'
    - '.ipynb_checkpoints'
    - '__pycache__'
    - '.vscode'
    - '.idea'
    - '.github'
    - 'venv'
    - 'env'
    - 'logs'
    - 'data'
    - 'output'

